repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-yaml
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: name-tests-test
      args: ['--django']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      stages: [commit]

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        stages: [ commit ]
