name: Continuous Integration

on:
  push:
    branches:
      - development

  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make dev_setup

      - name: Test with pytest
        run: |
          make test

      - name: Pre-Commit Hook Checking
        run: |
          pre-commit run --all-files
